/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package camera_rent;


/**
 *
 * @author micin
 */
public class Dashboard extends javax.swing.JFrame {
int row;
int total;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        LoadData ld = new LoadData();
        ld.loadKamera(tb_kamera);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tb_keranjang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_cancel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_kamera = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        total_harga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(657, 504));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tb_keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama Barang", "Harga", "Jumlah", "Total"
            }
        ));
        jScrollPane3.setViewportView(tb_keranjang);
        if (tb_keranjang.getColumnModel().getColumnCount() > 0) {
            tb_keranjang.getColumnModel().getColumn(0).setMinWidth(2);
            tb_keranjang.getColumnModel().getColumn(0).setPreferredWidth(2);
            tb_keranjang.getColumnModel().getColumn(0).setMaxWidth(2);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 320, 490, 150);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Keranjang :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 290, 110, 30);

        bt_cancel.setText("Cancel");
        bt_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cancelMouseClicked(evt);
            }
        });
        getContentPane().add(bt_cancel);
        bt_cancel.setBounds(530, 320, 120, 30);

        jButton4.setText("BAYAR");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(530, 440, 120, 30);

        tb_kamera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_kamera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_kameraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_kamera);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 660, 230);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KAMERAKU");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 670, 29);

        total_harga.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        total_harga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_harga.setText("0");
        getContentPane().add(total_harga);
        total_harga.setBounds(530, 400, 120, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Harga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 360, 120, 20);

        setSize(new java.awt.Dimension(680, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void bt_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cancelMouseClicked
        int b = tb_keranjang.getSelectedRow();
        Cancel ca = new Cancel();
        ca.batal(tb_keranjang,tb_kamera,b);
        int harga = ca.total;
        total = total-harga;
        total_harga.setText(Integer.toString(total));
        //ca.stok(tb_kamera,row);
    }//GEN-LAST:event_bt_cancelMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        new Pembayaran(total).setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void tb_kameraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_kameraMouseClicked
        row = tb_kamera.getSelectedRow();
        MasukKeranjang mk = new MasukKeranjang();
        mk.tambahKeranjang(tb_kamera,tb_keranjang,row, total_harga);
        int harga = mk.total;
        total = total+harga;
        total_harga.setText(Integer.toString(total));
    }//GEN-LAST:event_tb_kameraMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_kamera;
    private javax.swing.JTable tb_keranjang;
    private javax.swing.JLabel total_harga;
    // End of variables declaration//GEN-END:variables
}
